### PR TITLE
Readme.nit

### PR DESCRIPTION
**Pull request by marios**
Hi Dan, would it be helpful if I looked into making this ubuntu friendly? Alternatively I could take a stab at the iproute implementation, but not sure what you're working on,

thanks!

### CODE REVIEW

**Comment by dprince** [comment]
@marios My goal is to finish the impl_ifcfg.py first. It is almost done... just some additions for VLANs and an initial OVS bonding implementation. And then work on a CLI which will process raw JSON from heat metadata and use the os-net-config python library to configure things.

If you want to work on either the impl_iproute.py or impl_eni.py providers that would be great.

**Comment by marios** [comment]
OK thanks Dan, removed TODO. I am grabbing an Ubuntu image so I can hack on the impl_eni next week,

thanks!

**Comment by dprince** [comment]
@marios okay. You don't actually need an image for the initial work. All you have to do initially is match the config file formats we have here:
- ensure-bridge: http://git.openstack.org/cgit/openstack/tripleo-image-elements/tree/elements/netwo
  rk-utils/bin/ensure-bridge
- init-neutron-ovs: http://git.openstack.org/cgit/openstack/tripleo-image-elements/tree/elements/ne
  utron-openvswitch-agent/bin/init-neutron-ovs

**Comment by dprince** [comment]
@marios Okay. I merged only the readme changes.

The changes to parameterize the ifup/ifdown script locations causes unit test failures for me so I didn't merge it yet. Will add some comments inline.

**Comment by marios** [comment]
I didn't actually try to run the tests... will have a look once am in front of a computer likely Monday

**Comment by marios** [comment]
yeah so I tried that ('/usr/bin/which') .. put a pdb trace in there and invoked with tox -e venv -- python -m testtools.run os_net_config.tests.test_impl_ifcfg to catch the break. I tried (Pdb) processutils.execute('/usr/bin/which', 'ifdown')
but still no joy so decided not to chase this non-issue any longer. Was just trying to open a first pull request ;) i'll close this for now

**Pull request closed without merging**
